### PR TITLE
MODULE-1:TASK-1: Sum function

### PR DESCRIPTION
**Pull request by mozolevsky**
Function to sum two numbers.

### CODE REVIEW

**Comment by jsru** [comment]
Спасибо за отправленный пулриквест, теперь @tadjik1 должен запустить тесты.

**Comment by jsru** [comment]
Добавляю преподавателя (@tadjik1) для код-ревью.

**Comment by mozolevsky** [comment]
Since 1st pr is waiting for an approval and we work only in master the second pr after my push was automatically added to the current pr. If it's a problem i can revert changes of the 2nd task and push them later or can i can create the 2nd pr in an anoter branch. What is more suitable for you?

**Comment by jsru** [comment]
Решение было обновлено, посмотрим что скажет @tadjik1

**Comment by tadjik1** [comment]
@mozolevsky that's fine, and absolutely expected behaviour and do not worry - I see which tests were passed and which tasks you were working on, so I review only them.
Do not worry - just push & work on tasks as you wish, everything is fine from the taskbook infrastructure.

**Review by tadjik1 — APPROVED** [review]
well done 🥇

**Pull request merged**
